Traceback (most recent call last):
  File "/Users/uteamerstorfer/miniconda3/envs/epn-ml-book/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/uteamerstorfer/miniconda3/envs/epn-ml-book/lib/python3.9/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/uteamerstorfer/miniconda3/envs/epn-ml-book/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/uteamerstorfer/miniconda3/envs/epn-ml-book/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/uteamerstorfer/miniconda3/envs/epn-ml-book/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/uteamerstorfer/miniconda3/envs/epn-ml-book/lib/python3.9/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/Users/uteamerstorfer/miniconda3/envs/epn-ml-book/lib/python3.9/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/uteamerstorfer/miniconda3/envs/epn-ml-book/lib/python3.9/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#only use if GPU available

#Set devices_id
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID" 
os.environ["CUDA_VISIBLE_DEVICES"]="0"

import tensorflow as tf
tf.test.is_gpu_available()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/var/folders/x3/2bzh843n0tv469w6l6sd8sq00000gn/T/ipykernel_74758/790403423.py[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0mos[0m[0;34m.[0m[0menviron[0m[0;34m[[0m[0;34m"CUDA_VISIBLE_DEVICES"[0m[0;34m][0m[0;34m=[0m[0;34m"0"[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;34m[0m[0m
[0;32m----> 8[0;31m [0;32mimport[0m [0mtensorflow[0m [0;32mas[0m [0mtf[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0mtf[0m[0;34m.[0m[0mtest[0m[0;34m.[0m[0mis_gpu_available[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'tensorflow'
ModuleNotFoundError: No module named 'tensorflow'

